extern const GeoLayout totwc_area_1_geo[];
extern const GeoLayout totwc_area_1[];
extern const Collision totwc_area_1_collision[];
extern const MacroObject totwc_area_1_macro_objs[];
extern u8 totwc_dl_cloud_i8[];
extern u8 totwc_dl_bricks_i8[];
extern Vtx totwc_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx totwc_dl_Level_Mesh_mesh_layer_1_vtx_0[282];
extern Gfx totwc_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx totwc_dl_Level_Mesh_mesh_layer_1_vtx_1[520];
extern Gfx totwc_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx totwc_dl_Level_Mesh_mesh_layer_1_vtx_2[74];
extern Gfx totwc_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Gfx mat_totwc_dl_f3dlite_material_001[];
extern Gfx mat_revert_totwc_dl_f3dlite_material_001[];
extern Gfx mat_totwc_dl_f3dlite_material_002[];
extern Gfx mat_revert_totwc_dl_f3dlite_material_002[];
extern Gfx mat_totwc_dl_f3dlite_material_003[];
extern Gfx mat_revert_totwc_dl_f3dlite_material_003[];
extern Gfx totwc_dl_Level_Mesh_mesh_layer_1[];
