extern const GeoLayout sl_area_1_geo[];
extern const GeoLayout sl_area_1[];
extern const Collision sl_area_1_collision[];
extern const MacroObject sl_area_1_macro_objs[];
extern u8 sl_dl_ice_ci8[];
extern u8 sl_dl_ice_pal_rgba16[];
extern u8 sl_dl_snow_ci8[];
extern u8 sl_dl_snow_pal_rgba16[];
extern u8 sl_dl_rock_ci8[];
extern u8 sl_dl_rock_x_snow_edge_rock_pal_rgba16[];
extern u8 sl_dl_snow_edge_rock_ci8[];
extern u8 sl_dl_rock_pal_rgba16[];
extern u8 sl_dl_ice_light_ci8[];
extern u8 sl_dl_ice_light_pal_rgba16[];
extern Vtx sl_dl_Level_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx sl_dl_Level_Mesh_mesh_layer_5_vtx_0[8];
extern Gfx sl_dl_Level_Mesh_mesh_layer_5_tri_0[];
extern Vtx sl_dl_Level_Mesh_mesh_layer_5_vtx_1[252];
extern Gfx sl_dl_Level_Mesh_mesh_layer_5_tri_1[];
extern Vtx sl_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Level_Mesh_mesh_layer_1_vtx_0[773];
extern Gfx sl_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Level_Mesh_mesh_layer_1_vtx_1[687];
extern Gfx sl_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx sl_dl_Level_Mesh_mesh_layer_1_vtx_2[138];
extern Gfx sl_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Vtx sl_dl_Level_Mesh_mesh_layer_1_vtx_3[6];
extern Gfx sl_dl_Level_Mesh_mesh_layer_1_tri_3[];
extern Gfx mat_sl_dl_Burning_Ice[];
extern Gfx mat_revert_sl_dl_Burning_Ice[];
extern Gfx mat_sl_dl_Snow[];
extern Gfx mat_revert_sl_dl_Snow[];
extern Gfx mat_sl_dl_f3dlite_material_001_layer1[];
extern Gfx mat_revert_sl_dl_f3dlite_material_001_layer1[];
extern Gfx mat_sl_dl_f3dlite_material_002[];
extern Gfx mat_revert_sl_dl_f3dlite_material_002[];
extern Gfx mat_sl_dl_Ice_Crystal[];
extern Gfx mat_revert_sl_dl_Ice_Crystal[];
extern Gfx mat_sl_dl_Burning_Ice_001[];
extern Gfx mat_revert_sl_dl_Burning_Ice_001[];
extern Gfx sl_dl_Level_Mesh_mesh_layer_5[];
extern Gfx sl_dl_Level_Mesh_mesh_layer_1[];
