extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern u8 hmc_dl_milk_ci4[];
extern u8 hmc_dl_milk_pal_rgba16[];
extern u8 hmc_dl_oreo_i8[];
extern u8 hmc_dl_oreo_side_i8[];
extern Vtx hmc_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Level_Mesh_mesh_layer_1_vtx_0[8];
extern Gfx hmc_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Level_Mesh_mesh_layer_1_vtx_1[8];
extern Gfx hmc_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_Level_Mesh_mesh_layer_1_vtx_2[10];
extern Gfx hmc_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Vtx hmc_dl_Level_Mesh_mesh_layer_1_vtx_3[18];
extern Gfx hmc_dl_Level_Mesh_mesh_layer_1_tri_3[];
extern Gfx mat_hmc_dl_Bottom[];
extern Gfx mat_revert_hmc_dl_Bottom[];
extern Gfx mat_hmc_dl_Milk[];
extern Gfx mat_revert_hmc_dl_Milk[];
extern Gfx mat_hmc_dl_Oreo[];
extern Gfx mat_revert_hmc_dl_Oreo[];
extern Gfx mat_hmc_dl_Oreo_Side[];
extern Gfx mat_revert_hmc_dl_Oreo_Side[];
extern Gfx hmc_dl_Level_Mesh_mesh_layer_1[];
